codeon/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from students import urls as student_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(student_urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
]

students/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls.static import static
from django.conf.urls import url, patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from students.views import GroupListView, GroupCreate, GroupEdit, GroupDelete,\
    StudentListView, StudentCreate, StudentEdit, StudentDelete

urlpatterns = [
    url(r'^$', GroupListView.as_view(), name='group_list'),
    url(r'^group/create$', GroupCreate.as_view(), name='group_create'),
    url(r'^group/edit/(?P<pk>\d+)$', GroupEdit.as_view(), name='group_edit'),
    url(r'^group/delete/(?P<pk>\d+)$', GroupDelete.as_view(),
        name='group_delete'),
    url(r'^studentlist/(?P<pk>\d+)$', StudentListView.as_view(),
        name='student_list'),
    url(r'^studentlist/create$', StudentCreate.as_view(),
        name='student_create'),
    url(r'^studentlist/edit/(?P<pk>\d+)$', StudentEdit.as_view(),
        name='student_edit'),
    url(r'^studentlist/delete/(?P<pk>\d+)$', StudentDelete.as_view(),
        name='student_delete'),
]

if settings.DEBUG:
    urlpatterns += patterns('',
                            ) + static(settings.MEDIA_URL,
                                       document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

students/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
from django.core.exceptions import ValidationError
from django.utils.six import python_2_unicode_compatible

from util import models


def name_validator(full_name):
        """
        Checks is whether the full name consist of 3 words
        example : Иванов Николай Николаевич
        """
        reg = re.compile(
            u'^[а-яА-яa-zA-Z]+[\s]+[а-яА-яa-zA-Z]+[\s]+[а-яА-яa-zA-Z]+')
        if not reg.match(full_name) :
            raise ValidationError(u'Name {0} must be like '
                                  u'"Иванов Николай Николаевич"'
                                  .format(full_name))


@python_2_unicode_compatible
class Student(models.Model):
    full_name = models.CharField(blank=True,
                                 null=False,
                                 max_length=100,
                                 validators=[name_validator])
    photo = models.ImageField(upload_to='media/images')
    birth_date = models.DateTimeField(null=False)
    student_ticket_number = models.IntegerField(blank=False,
                                                null=False,
                                                default=0,
                                                unique=True)
    group = models.ForeignKey('Group',
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL)

    def __str__(self):
        return self.full_name


@python_2_unicode_compatible
class Group(models.Model):
    title = models.CharField(blank=True,
                             null=False,
                             max_length=100)
    steward = models.ForeignKey(Student,
                                related_name='steward',
                                related_query_name='steward',
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL)

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class EventHistory(models.Model):
    model = models.CharField(max_length=20,
                             blank=True,
                             null=False)
    related_id = models.IntegerField()
    event = models.CharField(max_length=10,
                             blank=True,
                             null=False)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.model

students/util/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.db.models import *
from sorl.thumbnail import ImageField

students/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.forms.extras import SelectDateWidget
from students.models import Student


class EditStudentForm(forms.ModelForm):
    class Meta(object):
        model = Student
        fields = ('full_name',
                  'photo',
                  'birth_date',
                  'student_ticket_number',
                  'group')

    def __init__(self, *args, **kwargs):
        super(EditStudentForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget = SelectDateWidget()


class CreateStudentForm(forms.ModelForm):
    class Meta(object):
        model = Student
        fields = ('full_name',
                  'photo',
                  'birth_date',
                  'student_ticket_number',
                  'group')

    def __init__(self, *args, **kwargs):
        super(CreateStudentForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget = SelectDateWidget()

students/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from students.forms import EditStudentForm, CreateStudentForm
from students.models import Group, Student


class GroupListView(ListView):
    model = Group


class GroupCreate(CreateView):
    model = Group
    success_url = reverse_lazy('group_list')
    fields = ['title', 'steward']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupCreate, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('student_list', args=(self.object.id,))


class GroupEdit(UpdateView):
    model = Group
    success_url = reverse_lazy('group_list')
    fields = ['title', 'steward']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupEdit, self).dispatch(request, *args, **kwargs)


class GroupDelete(DeleteView):
    model = Group
    success_url = reverse_lazy('group_list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupDelete, self).dispatch(request, *args, **kwargs)


class StudentListView(ListView):
    model = Student
    paginate_by = 2

    def get_queryset(self):
        return Student.objects.filter(group_id=self.kwargs['pk'])


class StudentCreate(CreateView):
    model = Student
    form_class = CreateStudentForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StudentCreate, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('student_list', args=(self.object.group.id,))


class StudentEdit(UpdateView):
    model = Student
    form_class = EditStudentForm
    success_url = reverse_lazy('student_list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StudentEdit, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('student_list', args=(self.object.group.id,))


class StudentDelete(DeleteView):
    model = Student
    success_url = reverse_lazy('student_list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(StudentDelete, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('student_list', args=(self.object.group.id,))


def logout_view(request):
    logout(request)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Students App{% endblock %}</title>

    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/custom.css">
</head>

<body>
{% block nav %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'group_list' %}"></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="menu" href="{% url 'group_list' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li>
                            <a class="logout" href="{% url 'logout' %}?next=/">LogOut</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="login" href="{% url 'login' %}">LogIn</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="list-group-item-heading">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>

</body>

</html>

templates/students/group_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input id="submit" name="submit" type="submit" value="Submin" class="btn btn-primary">
    </form>
{% endblock %}

templates/students/group_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input id="submit" name="submit" type="submit" value="Submin" class="btn btn-primary">
    </form>
{% endblock %}

templates/students/group_list.html
{% extends 'base.html' %}

{% load admin_tags %}

{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'group_create' %}">
            <button class="btn btn-success">Add Group</button>
        </a>
        <div class="clear" style="height: 20px;"></div>
    {% endif %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <td>Group</td>
            <td>Steward</td>
            <td>Students Count</td>
            {% if user.is_authenticated %}
                <td>Actions</td>
                <td>Admin panel actions</td>
            {% endif %}
        </tr>
        </thead>
        <tbody>
            {% for group in group_list %}
                <tr>
                    <td>
                        <a href="{% url 'student_list' group.id %}">
                            {{ group.title }}
                        </a>
                    </td>
                    <td>
                        {% if group.steward  %}
                            {{ group.steward }}
                        {% endif %}
                    </td>
                    <td>{{ group.student_set.count }}</td>
                {% if user.is_authenticated %}
                    <td>
                        <a href="{% url 'group_edit' group.id %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                        <a href="{% url 'group_delete' group.id %}">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </a>
                    </td>
                    <td>
                        {% admin_url group %}
                    </td>
                {% endif %}
                </tr>
            {% empty %}
                <td></td>
                <td>No articles yet.</td>
                <td></td>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/students/includes/paginator.html
{% load i18n %}
{% if is_paginated %}
	<div class="row col-lg-12">
	    <ul class="pager">
		    {% if page_obj.has_previous %}
		    	<li><a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a></li>
		    {% else %}
		    	<li class="disabled"><a href="#">{% trans "Previous" %}</a></li>
		    {% endif %}
		    <li class="number-of-pages">
			    {% blocktrans with page_number=page_obj.number total_pages=page_obj.paginator.num_pages %}
				    page {{ page_number }} of {{ total_pages }}
				{% endblocktrans %}
		    </li>
		    {% if page_obj.has_next %}
		    	<li><a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a></li>
		    {% else %}
		    	<li class="disabled"><a href="#">{% trans "Next" %}</a></li>
		    {% endif %}
	    </ul>
	</div>
{% endif %}

templates/students/student_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input id="submit" name="submit" type="submit" value="Submin" class="btn btn-primary">
    </form>
{% endblock %}

templates/students/student_form.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block content %}
   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <table>
            <tbody>
            <tr class="form-row">
                <td>
                    {% if form.full_name.errors %}
                        {% for error in form.full_name.errors %}
                            <p class="error"> {{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label class="col-sm-12 control-label">{{ form.full_name.label }}</label>
                </td>
                <td>
                    {{ form.full_name }}
                </td>
            </tr>
            <tr class="form-row">
                <td>

                    {% if form.photo.errors %}
                        {% for error in form.photo.errors %}
                            <p class="error"> {{ error }}</p>
                        {% endfor %}
                    {% endif %}
                     <label class="col-sm-12 control-label">{{ form.photo.label }}</label>
                </td>
                <td>
                    {{ form.photo }}
                </td>
            </tr>
            <tr class="form-row">
                <td>
                    {% if form.birth_date.errors %}
                        {% for error in form.birth_date.errors %}
                            <p class="error"> {{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label class="col-sm-12 control-label">{{ form.birth_date.label }}</label>
                </td>
                <td>
                    {{ form.birth_date }}
                </td>
            </tr>
            <tr class="form-row">
                <td class="form-row">
                    {% if form.student_ticket_number.errors %}
                        {% for error in form.student_ticket_number.errors %}
                            <p class="error"> {{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label class="col-sm-12 control-label">{{ form.student_ticket_number.label }}</label>
                </td>
                <td>
                    {{ form.student_ticket_number }}
                </td>
            </tr>
            <tr class="form-row">
                <td>
                    {% if form.group.errors %}
                        {% for error in form.group.errors %}
                            <p class="error"> {{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <label class="col-sm-12 control-label">{{ form.group.label }}</label>
                </td>
                <td>
                    {{ form.group }}
                </td>
            </tr>
            <tr class="form-row">
                <td></td>
                <td>
                    <input id="submit" name="submit" type="submit" value="Submin" class="btn btn-primary">
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

templates/students/student_list.html
{% extends 'base.html' %}

{% load admin_tags %}
{% load thumbnail %}

{% block content %}
    {% if user.is_authenticated %}
    <a href="{% url 'student_create' %}">
        <button class="btn btn-success">Add Student</button>
    </a>
    <div class="clear" style="height: 20px;"></div>
    {% endif %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <td>Name</td>
            <td>Photo</td>
            <td>Birth date</td>
            <td>Student ticket</td>
            {% if user.is_authenticated %}
                <td>Actions</td>
                <td>Admin panel actions</td>
            {% endif %}
        </tr>
        </thead>
        <tbody>
            {% for student in student_list %}
                <tr>
                    <td>
                        {{ student.full_name }}
                    </td>
                    <td>
                        {% thumbnail student.photo "100x100" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    </td>
                    <td>{{ student.birth_date|date:"d M Y" }}</td>
                    <td>{{ student.student_ticket_number }}</td>
                    {% if user.is_authenticated %}
                        <td>
                            <a href="{% url 'student_edit' student.id %}">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                            <a href="{% url 'student_delete' student.id %}">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </td>
                        <td>
                            {% admin_url student %}
                        </td>
                    {% endif %}
                </tr>
            {% empty %}
                <td></td>
                <td>No articles yet.</td>
                <td></td>
            {% endfor %}
        </tbody>
    </table>
    {% include "students/includes/paginator.html" %}
{% endblock %}